### ISSUE TITLE
About and Test buttons are switched in the menu bar

### ISSUE THREAD

**Issue by Jimmy-Tempest** [Emocial-NLP-Depression-Detection/Emocial-Frontend#26]
when clicking through the menu bars about and the test is unsoothingly change

**Comment by SiravitPhokeed** [comment]
I'm sorry Jimmy but I have zero idea of what you meant.

**Comment by Jimmy-Tempest** [comment]
like when you're in the testing tab and when you click either about or home it will go to the same page but difference id
we could switch place of them in the menu so about comes before test then it would be a bit nicer to navigate through the thing

**Comment by SiravitPhokeed** [comment]
The menu is going to be rearranged in issue #9 anyways so I'll implement this then.

**Comment by Jimmy-Tempest** [comment]
ok so close this?

**Comment by SiravitPhokeed** [comment]
I'll close it when I fix it.
